apiVersion: v1
kind: Pod
metadata:
  name: activity-12
spec:
  containers:
    - name: web
      image: nginx:1.27
    - name: sidecar
      image: alpine
      args: 
        - sleep
        - 1d

        # docker run -d alpine sleep 1d
        #docker run -d --entrypoint sleep alpine 1d 