---
apiVersion: v1
kind: Pod
metadata:
  name: activity5
spec:
  containers:
    - name: test
      image: alpine
      args: 
        - sleep
        - 1d
      env:
      - name: USERNAME
        value: admin
      - name: PASSWORD
        value: admin@123

#  kubectl apply -f activity5.yml
#  kubectl apply --dry-run=client -f activity5.yml
#  kubectl exec -c test  activity5 -- printenv
#  kubectl exec -c test  activity5 -- printenv

# kubectl get po -w 
