
# https://killercoda.com/playgrounds/scenario/kubernetes


apiVersion: v1
kind: Pod
metadata:
  name: hello-prod
Spec:
  containers:
  - name: web
    Image: nginx 1.27



---
apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
spec:
  containers:
    - name: web
      image: nginx:1.27

# to create prods from manifest 'kubectl apply -f <filename.yml>'


# kubectl get pods <pods-name>

  #kubectl get pods
  
  #kubectl get pods -o wide 

  # get podinfo in yaml format
      #kubectl describe hello-pod.yml
  
  #to watch the changes 
      #kuberctl get pods -w 

      




